### ISSUE TITLE
GFM asks for wrong answer

### ISSUE THREAD

**Issue by Stateford** [workshopper/how-to-markdown#1]
looking at the [question](https://github.com/denysdovhan/how-to-markdown/blob/master/exercises/gfm/en.md) it asks:

`Then mark item let's go as completed.`

however the [solution](https://github.com/denysdovhan/how-to-markdown/blob/master/exercises/gfm/solution/solution.md) requires `ho` to be checked

**Comment by denysdovhan** [comment]
Thanks for reporting. Fixed in `v1.0.1`.
