### ISSUE TITLE
trim trailling space of each line before compare with solution?

### ISSUE THREAD

**Issue by academyofzhuang** [workshopper/how-to-markdown#21]
I was stuck with a challenge.  Turned out to be one of my list item has a trailing space. 

But the hint (Difference ===================  ) doesn't show differences of spaces.

It's confusing to see that my attempt and solution is visually identical, but it failed the task.

Would it be better if you trim trailing space of each line before compare with solution?

``` bash
## Check your solution:  

  Solution ===================  

     # Lists  

     - One  
       - 1.1  
       - 1.2  
     - Two  
       - 2.1  
       - 2.2  
     - Three  
     - Four  
     - Five  

  Your Attempt ===================  

     # Lists  

     - One  
       - 1.1  
       - 1.2  
     - Two  
       - 2.1   
       - 2.2  
     - Three  
     - Four  
     - Five  

  Difference ===================  

     # Lists  

     - One  
       - 1.1  
       - 1.2  
     - Two  
       - 2.1   
       - 2.2  
     - Three  
     - Four  
     - Five  

```

**Comment by academyofzhuang** [comment]
Same problem with Code chanllenge. When copying the code '  const add = (a, b) => a + b;  ' from terminal to text editor, it's easy to copy one or two trailing spaces. It failed the test.

I had to open the solution.md and compare each line to figure out what went wrong.

``````

## Check your solution:  

  Solution ===================  

     # Code  

     ```js  
     const add = (a, b) => a + b;  


     `Your Attempt ===================`  

 # Code  

     const add = (a, b) => a + b;  


     `Difference ===================`  

 # Code  

     const add = (a, b) => a + b;  

``````

```
```

**Comment by denysdovhan** [comment]
Thank you for reporting!

Now trailing spaces will be highlighted as `inversed`.

![image](https://cloud.githubusercontent.com/assets/3459374/19386027/b06446ce-921a-11e6-89f8-12243b2b7b95.png)
