### ISSUE TITLE
Tables challenge

### ISSUE THREAD

**Issue by academyofzhuang** [workshopper/how-to-markdown#22]
In the introduction, it says: 

```
There are a few important things here:  

   » There must be at least 3 dashes separating each header cell.       

```

It says at least 3 dashes.

In the solution:

```
Solution ===================  

     # Tables  

     | Year | World population |  
     | :--: | ---------------- |  
     | 1960 | 3 Billion        |  

```

It uses two dashes in the 'Year' column.  Shall we add an exception to the rule ('align columns counts as dashes'), or just add one more dash to the solution to make it consistent.

**Comment by denysdovhan** [comment]
Good catch!

I think it would be better to add exception rule. Can you please send a PR?
