### ISSUE TITLE
Add NodeSchool deploy peeps to npm owners

### ISSUE THREAD

**Issue by llkats** [workshopper/how-to-markdown#25]
Please add @tdd and @julianduque to the [npm owner](https://github.com/orgs/workshopper/teams/deploy)s for this workshopper when you have a chance. Thanks!

**Comment by denysdovhan** [comment]
Done!

![image](https://cloud.githubusercontent.com/assets/3459374/19531637/fe592aaa-9640-11e6-8630-0372c4f71759.png)

But, please, keep me updated about releases.

**Comment by llkats** [comment]
Thanks, @denysdovhan!! I added you to the lead maintainers team. Keep up the good work!
