### ISSUE TITLE
Links solution code doesn't seem to work

### ISSUE THREAD

**Issue by nikzb** [workshopper/how-to-markdown#35]
The Links solution has the link reference as:

`[how-to-markdown]: git.io/how-to-markdown`

When I try this, the link doesn't work. 

Adding `http://` at the beginning of the link fixes it.

`[how-to-markdown]: http://git.io/how-to-markdown`

**Comment by itzsaga** [comment]
While more explanation in the Exercise could explain this, this should be changed as the tutorial is suppose to be very beginner friendly.

If this was deployed to the web the link would work. Without the `http://` the link you get when running `how-to-markdown run links.md` is sending your web browser to `http://localhost:3000/git.io/how-to-markdown`.

I personally prefer to use `//git.io/how-to-markdown` but that's neither here nor there.
