### ISSUE TITLE
How to translate menu items?

### ISSUE THREAD

**Issue by wangding** [workshopper/how-to-markdown#41]
Hi all, I'm new to here and want to make contributions.
Now I'm working on translating it to Chinese, hope it helpful.

A question is, how to translate the main menu? 

my work is here: https://github.com/wangding/how-to-markdown

**Comment by denysdovhan** [comment]
@wangding menu items are defined [here](https://github.com/workshopper/how-to-markdown/blob/master/index.js#L14-L25). Probably, there is a way to translate those items, but I don't know how. Try to find an example of menu translation in other workshoppers.

**Comment by denysdovhan** [comment]
Maybe @itzsaga can help?

**Comment by wangding** [comment]
i modify the i18n/zh-cn.json with following:

```javascript
{
  "title"    : "如何使用  Markdown",
  "subtitle" : "Markdown 非常神奇！"
  "exercise": {
        "HELLO WORLD":           "世界你好"
      , "HEADINGS":              "标题"
      , "EMPHASIS":              "强调"
      , "LISTS":                 "列表"
      , "LINKS":                 "超链接"
      , "IMAGES":                "图片"
      , "BLOCKQUOTES":           "引用"
      , "CODE":                  "代码"
      , "TABLES":                "表格"
      , "HORIZONTAL RULES":      "水平分隔线"
      , "HTML":                  "超文本"
      , "GFM":                   "GFM"
    }
}
```

it doesn't work

**Comment by itzsaga** [comment]
Waiting on internet to be installed in my new house. @denysdovhan, will take a look at this when I can review on my laptop (on my phone right now).

**Comment by denysdovhan** [comment]
@itzsaga no problems. Keep us updated.

**Comment by itzsaga** [comment]
@denysdovhan looks like other workshoppers are creating the menu differently.
Example from [javascripting](https://github.com/workshopper/javascripting/blob/master/index.js):
```js
jsing.addAll(require('./menu.json').map(function (problem) {
  return {
    name: problem,
    fn: function () {
      var p = problem.toLowerCase().replace(/\s/g, '-');
      var dir = require('path').join(__dirname, 'problems', p);
      return require(dir);
    }
  }
}))
```
Then there is a `menu.json` file in the root.
Then `i18n/zh-cn.json` would be:
```js
{
  "exercise": {
        "HELLO WORLD":           "世界你好"
      , "HEADINGS":              "标题"
      , "EMPHASIS":              "强调"
      , "LISTS":                 "列表"
      , "LINKS":                 "超链接"
      , "IMAGES":                "图片"
      , "BLOCKQUOTES":           "引用"
      , "CODE":                  "代码"
      , "TABLES":                "表格"
      , "HORIZONTAL RULES":      "水平分隔线"
      , "HTML":                  "超文本"
      , "GFM":                   "GFM"
    }
}
```
Pretty big change. What do you think?

**Comment by denysdovhan** [comment]
@itzsaga looks like an acceptable solutions :+1:
