### ISSUE TITLE
something wrong here

### ISSUE THREAD

**Issue by wangding** [workshopper/how-to-markdown#45]
following is parts of exercises/images/solution/en.md

>Now you learned how to create a link in Markdown. This is a common style for links, but some parsers provide additional tools for alignment, adding classes and other styles.

The challenage is about **image**, so the finished message maybe about **image** too.

**Comment by denysdovhan** [comment]
Yes, seems like this. Could you send a PR?

**Comment by wangding** [comment]
I am sorry, my english is poor. only can read something. 😭

**Comment by denysdovhan** [comment]
@wangding hmm, strange. How did you translate the workshopper then?

**Comment by wangding** [comment]
I offten reading IT articals in Internet, so I can reading something. But have little to write or speak in English. Please trust me.🙏 @denysdovhan

**Comment by denysdovhan** [comment]
That's okay. Nevermind 😉
