### ISSUE TITLE
correct solution not accepted - correct EOL required

### ISSUE THREAD

**Issue by nl-x** [workshopper/how-to-markdown#51]
The first exercise "HELLO WORLD" in how-to-markdown workshopper states as challenge:

>You first challenge is pretty simple. Just create a new file (for example
using touch) and add a single line:
  Hello, world!
If you already did this, run how-to-markdown verify to verify your
solution or how-to-markdown run to run your file in the browser.

Notice how the challenge explicitly mentions "a single line".
After completing the exercise the solution is not accepted.
It appears a linefeed (\n) at the end is required, effectively creating an empty second line.
To add insult to injury, in Windows an extra carriage return is given with the linefeed (\r\n), that also invalidates the solution.

The same issue also exists in other exercises within the workshopper.

Suggested fix would be to not require an EOL at the end of the solution.
And to translate all \r\n into \n (windows), and left over \r into \n (macintosh) in the attempted solutions before matching.

**Comment by denysdovhan** [comment]
Thanks for reaching out!

I've noticed that `{ position: false }` doesn't affect to output. It still keep position information in AST. 

@wooorm, I'm guessing you've changed the API? Unfortunately, can't find related options for `unified` or `remark`. Can you help?

**Comment by wooorm** [comment]
Hi! 👋

If you use `remark-parse` directly, it’s simplest (L37):

```diff
   const parseAST = str =>
-     Promise.resolve(remark().parse(str, { position: false }));
+     Promise.resolve(unified().use(parse, { position: false }).parse(str));
```

...or, with the current set-up:

```diff
   const parseAST = str =>
-     Promise.resolve(remark().parse(str, { position: false }));
+     Promise.resolve(remark().data('settings', { position: false }).parse(str));
```

**Comment by schellingerhout** [comment]
What about converting attempt files from CRLF to just LF?
 `const attempt = fs.readFileSync(filename, 'utf8').replace('\r\n', '\n');`

**Comment by wooorm** [comment]
Yeah I think that's a good solution to line endings!

**Comment by denysdovhan** [comment]
@schellingerhout please, check the latest version from `master`. Works fine for me.

**Comment by nl-x** [comment]
Shouldn't left-over \r (macintosh) also be replaced by a \n, as I had mentioned in the first post? Or is that ancient history?
(If you're going to do this, make sure it happens only **after** the \r\n=>\n replace.)

**Comment by wooorm** [comment]
I think that’s [ancient history](https://en.wikipedia.org/wiki/Newline#Representations) indeed!
