### ISSUE TITLE
End users unlikely to type an "Em Dash" in BlockQuotes exercise as required by the solution

### ISSUE THREAD

**Issue by schellingerhout** [workshopper/how-to-markdown#53]
Commit fca73c066a67d1296bafae678b699c01aa26cd3a changed the solution for Blockquotes exercise to use Em Dash. Its unlikely that an end-user would type an Em Dash or an En Dash. This leads to a confusing error that is hard to decipher. Its also hard to generate an Em Dash in most text editors without a character map

Instructions simply state 
"And add an original author to the quote right on the next line after this quote."

Likely user experience

So the user's first attempt will likely omit the dash. (Per instructions)
The diff will show a dash missing.
The user will attempt to correct and most likely type a simple Figure Dash.
This attempt which will fail with a diff that is hard to decipher. 

For reference:
Em Dash : — 
En Dash : – 
Figure Dash: -

**Comment by itzsaga** [comment]
Will take a look at tomorrow. What do you think is best @denysdovhan?

**Comment by denysdovhan** [comment]
@itzsaga em-dash isn't OK definitely, but simple minus-sign will produce a list item ¯\_(ツ)_/¯

**Comment by wooorm** [comment]
How about no newline? No hyphen/dash at all?

**Comment by denysdovhan** [comment]
@wooorm this exercise is about _block_quotes, so I've aimed to show, that we can put a bunch of paragraphs under `>`.

**Comment by wooorm** [comment]
Agreed, but then if we do:

> To be, or not to be, that is the question. (William Shakespeare)

...or:

> To be, or not to be, that is the question.
> William Shakespeare

...it wouldn’t matter, right?

**Comment by denysdovhan** [comment]
@schellingerhout fixed, and published as`v1.4.2`. Thanks for reporting!
