### ISSUE TITLE
Not being rendered properly

### ISSUE THREAD

**Issue by bythckr** [workshopper/how-to-markdown#57]
The page is not being rendered properly for me. What could be the issue? I am using iterm on osx. Any other info needed?
The the way I view it:
<img width="735" alt="screen shot 2017-04-04 at 13 46 56" src="https://cloud.githubusercontent.com/assets/26061980/24651185/f527202e-193d-11e7-9c10-b111d87f8e6f.png">

When I select the whole page using mouse:
<img width="627" alt="screen shot 2017-04-04 at 13 54 15" src="https://cloud.githubusercontent.com/assets/26061980/24651294/5f1c3b5e-193e-11e7-813c-59192353c506.png">

**Comment by denysdovhan** [comment]
This is an [msee](https://github.com/firede/msee) related issue.

cc/ @martinheidegger @firede

**Comment by martinheidegger** [comment]
This is a an iTerm and solarized issue, change your contrast settings! This is an well known issue, unfortunately finding colors that work without problem in all major theme/os/terminal is really tough. PR welcome

**Comment by denysdovhan** [comment]
Then I close this issue.
